apiVersion: v1
kind: Service
metadata:
  name: softethervpn
  labels:
    run: softethervpn
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
spec:
  selector:
    run: softethervpn
  ports:
    - protocol: UDP
      port: 4500
      targetPort: 4500
      name: udp-4500
    - protocol: UDP
      port: 500
      targetPort: 500
      name: udp-500
    - protocol: UDP
      port: 1701
      targetPort: 1701
      name: udp-1701
    - protocol: UDP
      port: 443
      targetPort: 443
      name: tcp-443
  type: LoadBalancer