apiVersion: v1
kind: Service
metadata:
  name: softethervpn
  labels:
    run: softethervpn
spec:
  selector:
    run: softethervpn
  ports:
    - protocol: UDP
      port: 4500
      targetPort: 4500
      name: udp-4500
    - protocol: UDP
      port: 500
      targetPort: 500
      name: udp-500
    - protocol: UDP
      port: 1701
      targetPort: 1701
      name: udp-1701
  type: LoadBalancer